const items = [
  {
    id: 1,
    image: "/stickerBag/angry.png",
    name: "Angry",
    price: "10.00",
    dimensions: "10x10",
  },
  {
    id: 2,
    image: "/stickerBag/angry1.png",
    name: "Angry 1",
    price: "15.00",
    dimensions: "15x15",
  },
  {
    id: 3,
    image: "/stickerBag/apple.png",
    name: "Apple",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 4,
    image: "/stickerBag/balloon.png",
    name: "Balloon",
    price: "10.00",
    dimensions: "10x10",
  },
  {
    id: 5,
    image: "/stickerBag/bath.png",
    name: "Bath",
    price: "15.00",
    dimensions: "15x15",
  },
  {
    id: 6,
    image: "/stickerBag/blushing.png",
    name: "Blushing",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 7,
    image: "/stickerBag/burger.png",
    name: "Burger",
    price: "10.00",
    dimensions: "10x10",
  },
  {
    id: 8,
    image: "/stickerBag/cat.png",
    name: "Cat",
    price: "15.00",
    dimensions: "15x15",
  },
  {
    id: 9,
    image: "/stickerBag/cherry.png",
    name: "Cherry",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 10,
    image: "/stickerBag/clapboard.png",
    name: "Clapboard",
    price: "10.00",
    dimensions: "10x10",
  },
  {
    id: 11,
    image: "/stickerBag/coffee.png",
    name: "Coffee",
    price: "15.00",
    dimensions: "15x15",
  },
  {
    id: 12,
    image: "/stickerBag/corgi.png",
    name: "Corgi",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 13,
    image: "/stickerBag/corgi1.png",
    name: "Corgi 1",
    price: "10.00",
    dimensions: "10x10",
  },
  {
    id: 14,
    image: "/stickerBag/corgi2.png",
    name: "Corgi 2",
    price: "15.00",
    dimensions: "15x15",
  },
  {
    id: 15,
    image: "/stickerBag/cry.png",
    name: "Cry",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 16,
    image: "/stickerBag/cute.png",
    name: "Cute",
    price: "10.00",
    dimensions: "10x10",
  },
  {
    id: 17,
    image: "/stickerBag/cute1.png",
    name: "Cute 1",
    price: "15.00",
    dimensions: "15x15",
  },
  {
    id: 18,
    image: "/stickerBag/eat.png",
    name: "Eat",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 19,
    image: "/stickerBag/emoticon.png",
    name: "Emoticon",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 20,
    image: "/stickerBag/frog.png",
    name: "Frog",
    price: "10.00",
    dimensions: "10x10",
  },
  {
    id: 21,
    image: "/stickerBag/grape.png",
    name: "Grape",
    price: "15.00",
    dimensions: "15x15",
  },
  {
    id: 22,
    image: "/stickerBag/happy.png",
    name: "Happy",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 23,
    image: "/stickerBag/happy1.png",
    name: "Happy 1",
    price: "10.00",
    dimensions: "10x10",
  },
  {
    id: 24,
    image: "/stickerBag/heart.png",
    name: "Heart",
    price: "15.00",
    dimensions: "15x15",
  },
  {
    id: 25,
    image: "/stickerBag/hello.png",
    name: "Hello",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 26,
    image: "/stickerBag/hi.png",
    name: "Hi",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 27,
    image: "/stickerBag/hide.png",
    name: "Hide",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 28,
    image: "/stickerBag/love.png",
    name: "Love",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 29,
    image: "/stickerBag/love1.png",
    name: "Love 1",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 30,
    image: "/stickerBag/paper-plane.png",
    name: "Paper Plane",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 31,
    image: "/stickerBag/pray.png",
    name: "Pray",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 32,
    image: "/stickerBag/proud.png",
    name: "Proud",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 33,
    image: "/stickerBag/rabbit.png",
    name: "Rabbit",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 34,
    image: "/stickerBag/reading-book.png",
    name: "Reading Book",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 35,
    image: "/stickerBag/skincare.png",
    name: "Skincare",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 36,
    image: "/stickerBag/smile.png",
    name: "Smile",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 37,
    image: "/stickerBag/stationary.png",
    name: "Stationary",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 38,
    image: "/stickerBag/tea-bag.png",
    name: "Tea Bag",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 39,
    image: "/stickerBag/watermelon.png",
    name: "Watermelon",
    price: "20.00",
    dimensions: "20x20",
  },
  {
    id: 40,
    image: "/stickerBag/weights.png",
    name: "Weights",
    price: "20.00",
    dimensions: "20x20",
  }
];

export default items;
